### ISSUE TITLE
ExPlasma.Utxo.new is fine with zero inputs and unpadded inputs

### ISSUE THREAD

**Issue by pdobacz** [omgnetwork/ex_plasma#19]
```
iex(24)> ExPlasma.Utxo.new(<<1::128>>)
%ExPlasma.Utxo{
  amount: 0,
  blknum: 0,
  currency: "0x0000000000000000000000000000000000000000",
  oindex: 1,
  output_type: 1,
  owner: "0x0000000000000000000000000000000000000000",
  txindex: 0
}
iex(25)> ExPlasma.Utxo.new(<<0::256>>)
%ExPlasma.Utxo{
  amount: 0,
  blknum: 0,
  currency: "0x0000000000000000000000000000000000000000",
  oindex: 0,
  output_type: 1,
  owner: "0x0000000000000000000000000000000000000000",
  txindex: 0
}
```

while neither should be legal, at least as far the requirements of https://github.com/omisego/elixir-omg/blob/master/apps/omg/lib/omg/utxo/position.ex#L171 go.

Note also that https://github.com/omisego/elixir-omg/blob/master/apps/omg/lib/omg/utxo/position.ex#L98 seems to not dispatch to `ExPlasma` at all, I think this has been mentioned to been not yet done. After this issue here is resolved I think `elixir-omg` should be tidied according to the resolution here.

This slipped under the tests in `elixir-omg` because of #18 - the test covering zero-inputs was generating malformed transactions for unrelated reasons.

**Comment by mederic-p** [comment]
This seems to be fixed now:
```
output = %ExPlasma.Output{ 
  output_data: %{
    amount: 0,
    output_guard: <<205, 193, 229, 59, 220, 116, 187, 245, 181, 247, 21, 214, 50, 125, 202, 87, 133, 226, 40, 180>>,
    token: <<0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0>>
  },
  output_id: nil,
  output_type: 1
}
ExPlasma.Output.validate(output)
```

Produces

```
{:error, {:amount, :cannot_be_zero}}
```
