### ISSUE TITLE
Match field naming with that of plasma-contracts

### ISSUE THREAD

**Issue by achiurizo** [omgnetwork/ex_plasma#24]
:clipboard: https://github.com/omisego/elixir-omg/issues/1237

We should match our field names with that of [plasma-contracts](https://github.com/omisego/plasma-contracts) to avoid confusion. Some naming different that were picked up in `elixir-omg` (and now here) are as follows(not full list):

elixir-omg | plasma-contracts
----------  | -----------------
owner | output_guard
currency | token

**Comment by ayrat555** [comment]
@achiurizo this issue seems resolved. will you close it?

**Comment by achiurizo** [comment]
Yep thank you! @ayrat555
