### ISSUE TITLE
Retrieve constant values from the contract instead of hard-coding it in code

### ISSUE THREAD

**Issue by achiurizo** [omgnetwork/ex_plasma#26]
📋 https://github.com/omisego/ex_plasma/pull/23#discussion_r365695555

We should have the library pull the constant values from the contract directly instead of duplicating the value and hard-coding it here.

**Comment by mederic-p** [comment]
It seems that the constants we are talking about in https://github.com/omisego/ex_plasma/pull/23#discussion_r365695555 are all internal and not retrievable externally. (https://github.com/omisego/plasma-contracts/blob/705f8dedc62c0747abeb54b14f076c90b6cba99e/plasma_framework/contracts/src/utils/PosLib.sol#L16)

Would it be better retrieve them from the config anyway? If so, should they have a default value in this library or is it the integrator's responsibility to define them?
